# Generated by Django 2.2.10 on 2020-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_data', '0002_auto_20200328_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnndata',
            name='pnn_time',
            field=models.FloatField(default=3, verbose_name='pnn_time'),
            preserve_default=False,
        ),
    ]
