# Generated by Django 2.2.10 on 2020-03-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_data', '0004_auto_20200331_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnndata',
            name='pnn_time',
        ),
    ]
