# Generated by Django 2.2.10 on 2020-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='start_time',
            field=models.TimeField(verbose_name='start_time'),
        ),
    ]
