# Generated by Django 2.2.10 on 2020-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20200328_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='start_time',
            field=models.DateTimeField(verbose_name='start_time'),
        ),
    ]
